users: 
    base: src/main/resources/users.json
    for-update: src/main/resources/update.json
messages:
    valid: src/main/resources/messages.json
    invalid: src/main/resources/invalid-messages.json
spring:
    profiles:
        active: test, default